conf/urls.py
from django.contrib import admin
from django.urls import path, include

# HtmlResponse を返すためのモジュールをインポート
from django.http import HttpResponse

# プロジェクト全体の設定情報を読み込みするための設定
from django.conf import settings

# スタティックURLを設定するためのモジュールをインポート
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # myappのURL設定を利用できるようにする
    # path('URLの条件、パターン', include('条件に一致したときに処理を引き渡すファイル') )
    # localhost/myapp/... にアクセスされたら、それ以降の内容をmyapp/urls.pyのパスとして解釈させる
    path('myapp/', include('myapp.urls')),

    path('myapp2/' , include('myapp2.urls')),
    
    # crud のアプリケーションの内容へ処理を引き渡す
    path('crud/', include('crud.urls')),
    
    # ユーザー認証用の機能を持たせたアプリケーションへ処理を引き渡す
    path('accounts/', include('accounts.urls'))
    
]

# 開発環境などであれば、スタティックURLを利用できるようにする
# /media/... のURLにアクセスされたら、 Djangoのプロジェクトのmedia ディレクトリの内容を参照するように関連付けを設定する
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

crud/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
 
app_name = 'crud'

urlpatterns = [
    # path('goods_create/', login_required(views.GoodsCreate.as_view()), name='goods_create'),
    path('goods_create/', views.GoodsCreate.as_view(), name='goods_create'),
    
    # path('goods_list/', login_required(views.GoodsList.as_view()), name='goods_list'),
    # path('goods_detail/<int:pk>/', login_required(views.GoodsDetail.as_view()), name='goods_detail'),
    path('goods_list/', views.GoodsList.as_view(), name='goods_list'),
    path('goods_detail/<int:pk>/', views.GoodsDetail.as_view(), name='goods_detail'),
    path('goods_update/<int:pk>/', views.GoodsUpdate.as_view(), name='goods_update'),

    # 論理削除するビューを呼び出すルーティング
    path('goods_delete/<int:pk>/', views.CustomDeleteView.as_view(), name='goods_delete'),

    # 物理削除するビューを呼び出すルーティング
    # path('goods_delete/<int:pk>/', views.GoodsDelete.as_view(), name='goods_delete'),
]

crud/models.py
from django.db import models
from django.core.validators import MaxValueValidator
 
class Goods(models.Model):
    name = models.CharField('商品名', unique=True, max_length=10, null=True)
    management_code = models.CharField('管理コード', unique=True, max_length=20)
    price = models.PositiveIntegerField('価格', validators=[MaxValueValidator(1000000000)])
    release_date = models.DateField('発売日', blank=True, null=True)
    release_flag = models.BooleanField('発売済み', default=False)
    description = models.CharField('商品説明', max_length=100000)
    image = models.ImageField('商品画像', null=True, blank=True, upload_to='goods_images/')
    state_flag = models.BooleanField('運用状況', default=True)
 
    def __str__(self):
        return self.name
    
    # 論理削除を行うためのメソッドを用意する
    def custom_delete(self):
        self.state_flag = False
        self.save()

crud/forms.py
from django import forms
from .models import Goods
 
class GoodsCreateForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ('name', 'management_code', 'price', 'release_date', 'release_flag', 'description', 'image')

# 更新画面用のフォームクラス
class GoodsUpdateForm(forms.ModelForm):
    class Meta:
        model = Goods
        fields = ('name', 'management_code', 'price', 'release_date', 'release_flag', 'description', 'image')

crud/views.py
from django.shortcuts import render

from django.views import generic
from .forms import GoodsCreateForm

from .forms import GoodsUpdateForm

# リダイレクトを実行するためのモジュールをインポートしておく
from django.http import HttpResponseRedirect

# from .forms import GoodsCreateForm, GoodsUpdateForm, ImageSizeLimitationForm
 
# Goodsモデルが使えるようにインポート
from .models import Goods

class GoodsCreate(generic.CreateView):
    form_class = GoodsCreateForm
    template_name = 'crud/goods_create.html'
    success_url = '/crud/goods_create' # レコード保存に成功したらこのurlにリダイレクトする

class GoodsList(generic.ListView):
    model = Goods
    template_name = 'crud/goods_list.html'
 
class GoodsDetail(generic.DetailView):
    model = Goods

class GoodsUpdate(generic.UpdateView):
    model = Goods
    form_class = GoodsUpdateForm
    template_name = 'crud/goods_update.html'
    success_url = '/crud/goods_list'

# 論理削除(削除フラグを切り替える)のViewクラス
class CustomDeleteView(generic.DeleteView):
    model = Goods
    template_name = 'crud/goods_delete.html'
    success_url = '/crud/goods_list'
    
    # 削除の処理をオーバーライドする
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.custom_delete()
        return HttpResponseRedirect(success_url)


# 物理削除(レコード自体を削除する)のViewクラス
class GoodsDelete(generic.DeleteView):
    model = Goods
    template_name = 'crud/goods_delete.html'
    success_url = '/crud/goods_list'

templates/crud/goods_create.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品作成ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="作成">
</form>
 
{% endblock %}

templates/crud/goods_delete.html
{% extends 'base.html' %}
 
{% block content %}
<form method="post">{% csrf_token %}
    <p>"{{ object }}"を削除してもよろしいですか?</p>
    <input type="submit" value="削除">
</form>
 
{% endblock %}

templates/crud/goods_detail.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品名:{{ object.name }}</h2>
{% if object.image %}
  <p>商品画像:</p><img src="{{ object.image.url }}/">
{% endif %}
<p>管理番号:{{ object.management_code }}</p>
<p>価格:{{ object.price }}</p>
<p>発売日:{{ object.release_date }}</p>
<p>発売状況{{ object.release_flag }}</p>
<p>商品説明：{{ object.description }}</p>
<p>運用状況：{{ object.state_flag }}</p>
 
{% endblock %}

templates/crud/goods_list.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品リスト
<a href="{% url 'crud:goods_create' %}">作成</a>
{% for goods in goods_list %}
  {% if goods.state_flag %}
    <p>
      {{ goods.name }}
      /<a href="{% url 'crud:goods_update' goods.id %}">更新</a>
      /<a href="{% url 'crud:goods_detail' goods.id %}">詳細</a>
      /<a href="{% url 'crud:goods_delete' goods.id %}">削除</a>
    </p>
  {% endif %}
{% endfor %}
 
{% endblock %}

templates/crud/goods_update.html
{% extends 'base.html' %}
 
{% block content %}
<h2>商品情報更新ページ</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" id="save" value="更新">
</form>
 
{% endblock %}