conf/urls.py
from django.contrib import admin
from django.urls import path, include

# HtmlResponse を返すためのモジュールをインポート
from django.http import HttpResponse

# プロジェクト全体の設定情報を読み込みするための設定
from django.conf import settings

# スタティックURLを設定するためのモジュールをインポート
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # myappのURL設定を利用できるようにする
    # path('URLの条件、パターン', include('条件に一致したときに処理を引き渡すファイル') )
    # localhost/myapp/... にアクセスされたら、それ以降の内容をmyapp/urls.pyのパスとして解釈させる
    path('myapp/', include('myapp.urls')),

    path('myapp2/' , include('myapp2.urls')),
    
    # crud のアプリケーションの内容へ処理を引き渡す
    path('crud/', include('crud.urls')),
    
    # ユーザー認証用の機能を持たせたアプリケーションへ処理を引き渡す
    path('accounts/', include('accounts.urls'))
    
]

# 開発環境などであれば、スタティックURLを利用できるようにする
# /media/... のURLにアクセスされたら、 Djangoのプロジェクトのmedia ディレクトリの内容を参照するように関連付けを設定する
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

myapp2/urls.py
# URLのパターンの解析ができるように、path をインポートしておく
from django.urls import path

# views.py をインポート
from . import views

app_name = 'myapp2'

urlpatterns = [
	path('staff_information_create/', views.StaffInformationCreateView.as_view(), name='staff_information_create'),
    path('staff_create/', views.StaffCreateView.as_view(), name='staff_create'),

    path('staff_list/', views.StaffListView.as_view(), name='staff_list'),   
    path('staff_update/<int:pk>', views.StaffUpdateView.as_view(), name='staff_update'),   
]

myapp2/models.py
from django.db import models

# Create your models here.
 
# 従業員一人についての詳細データ
class StaffInformation(models.Model):
    staff_name = models.CharField('名前', max_length=100)
    email = models.EmailField('メールアドレス', blank=True, null=True)
    address = models.CharField('住所', blank=True, null=True, max_length=100)
    birthday = models.DateTimeField('誕生日', blank=True, null=True)
    hire_date = models.DateField('入社日', blank=True, null=True)
    at_desk = models.BooleanField('出社状態', default=False)
 
    def __str__(self):
        return self.staff_name

# 部署の一覧テーブル
# staff_informationの側で、foreign keyを持っている
class Department(models.Model):
    name = models.CharField('部署名', unique=True, max_length=100)
    def __str__(self):
        return self.name

# 会社の所有書籍のデータ
class Book(models.Model):
    name = models.CharField('書籍名', max_length=100)
    management_code = models.CharField('管理番号', unique=True, max_length=50)
 
    def __str__(self):
        return self.name

# 従業員のデータ
class Staff(models.Model):
    name = models.CharField('ビジネスネーム', max_length=100)
    information = models.OneToOneField(StaffInformation, on_delete=models.CASCADE, verbose_name=("社員情報"), null=True)
    
    # 部署のテーブルとの関連付けを表現するリレーションの設定
    # Staffからみると、所属する部署はひとつだけなので、多対一の関連になる
    # ForeignKey(連携先のモデル名, on_delete=削除されたときの動作)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=("所属部署"), null=True)
 
    # 会社の書籍のテーブルとの可憐付けを表現するリレーション
    # 履歴として考えたとき、一冊の本が過去に他の社員さんに借りられている場合があるので、多対多の関連になる
    # MenyToManyFileld(<連携先モデル名>)
    rented_books = models.ManyToManyField(Book, verbose_name=("借りている本"))
 
    def __str__(self):
        return self.name

myapp2/forms.py
from django import forms
from .models import StaffInformation, Staff

# 従業員の詳細情報を作成するフォーム
class StaffInformationForm(forms.ModelForm):
    class Meta:
        model = StaffInformation
        fields = ('staff_name','email', 'address', 'birthday', 'hire_date', 'at_desk')

# 従業員の基本情報を作成するフォーム
class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ('name', 'rented_books', 'information')

myapp2/views.py
from django.views.generic import CreateView, DetailView, UpdateView, FormView, ListView
from django.urls import reverse_lazy
from .models import StaffInformation, Staff
from .forms import StaffInformationForm, StaffForm

# 社員の詳細情報を作成するための画面のビュー
class StaffInformationCreateView(CreateView):
    model = StaffInformation
    form_class = StaffInformationForm
    template_name = 'myapp2/staff_information_create.html'
    success_url = reverse_lazy('myapp:home')

# 社員の基本情報を作成するための画面のビュー
class StaffCreateView(CreateView):
    model = Staff
    form_class = StaffForm
    template_name = 'myapp2/staff_create.html'
    success_url = reverse_lazy('myapp:home')

# 社員の基本情報を一覧表示する画面のビュー
class StaffListView(ListView):
    model = Staff
    template_name = 'myapp2/staff_list.html'

# 社員の編集画面のビュー
class StaffUpdateView(UpdateView):
    model = Staff
    form_class = StaffForm
    template_name = 'myapp2/staff_update.html'
    success_url = reverse_lazy('myapp2:staff_list')

templates/myapp2/staff_create.html
<!doctype html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>Python 講座</title>
</head>
<body>
<h1>社員作成ページ</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="作成">
</form>
</body>
</html>

templates/myapp2/staff_information_create.html
<!doctype html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>Python 講座</title>
</head>
<body>
<h1>社員情報作成ページ</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="作成">
</form>
</body>
</html>

templates/myapp2/staff_list.html
<h1>社員リスト</h1>

<table border='1'>

	<tr>
		<td>id</td>
		<td>ビジネスネーム</td>
		<td>所属部署名</td>
		<td>借りている本</td>
		<td>編集</td>
		<td>削除</td>
	</tr>

	{% for staff in staff_list %}
		<tr>
			<td>{{ staff.id }}</td>
			<td>{{ staff.name }}</td>
			<td>{{ staff.department.name }}</td>
			<td>
				<ul>
					{% for book in staff.rented_books.all %}
						<li>{{ book.name }} (管理コード: {{ book.management_code }}) </li>
					{% endfor %}
				</ul>
			</td>
			<td> <a href="{% url 'myapp2:staff_update' staff.id %}">編集</a> </td>
			<td></td>
		</tr>
	{% endfor %}

</table>

templates/myapp2/staff_update.html
<!doctype html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>Python 講座</title>
</head>
<body>
<h1>社員編集ページ</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
</form>
</body>
</html>